# Generated by Django 4.2.7 on 2025-08-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('to', models.TextField()),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_processor_ai_app.emailrecord')),
            ],
        ),
    ]
