# Generated by Django 4.2.7 on 2025-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_processor_ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='email_type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
