# Generated by Django 4.2.7 on 2025-08-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_processor_ai_app', '0002_emailrecord_email_type'),
    ]

    operations = [
    ]
