# Generated by Django 4.2.7 on 2025-08-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_processor_ai_app', '0003_auto_20250812_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('screening_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('resume_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
